### ISSUE TITLE
devise-token-auth parameters and responses

### ISSUE THREAD

**Issue by augustosamame** [rubymotion-community/motion-authentication#2]
Hi. I have forked this repo to use it in my project and notice that the current devise_token_auth strategy does not match the current version (v 0.1.37) of the devise_token_auth gem.
User and Email parameters are POSTed to sign_in url but should not be wrapped in a user hash.
Response will include access-token, uid and client field as Header responses, not as fields in the JSON body.
I think this version may be deprecated?
I will make the necessary updates and send a PR if you're interested in updating this. It's certainly a very useful library.

**Comment by andrewhavens** [comment]
Hi @augustosamame,

Thanks for using `motion-authentication`! Unfortunately, the `devise_token_auth` gem is [one of many "Devise token auth" implementations](https://github.com/plataformatec/devise/wiki/How-To:-Simple-Token-Authentication-Example). The `:devise_token_auth` strategy that `motion-authentication` expects was originally based on [José Valim's example gist](https://gist.github.com/josevalim/fb706b1e933ef01e4fb6) and is also in the format that Ember Simple Auth Devise adapter expects ([tutorial](http://romulomachado.github.io/2015/09/28/using-ember-simple-auth-with-devise.html)). This should probably be mentioned in more detail in the README.

However, I would be more than happy to accept a PR which adds another strategy and/or adds more clarification to the README.

Thanks!

**Comment by augustosamame** [comment]
Got it. Will add another strategy referencing the devise_token_auth gem.
